name: diim_py
channels:
 - conda-forge
dependencies:
 - python == 3.9
 - ConfigSpace>=1.1.1
 - matplotlib>=3.7
 - matplotlib-inline>=0.1.7
 - mdurl>=0.1.2
 - multiprocess>=0.70.16
 - numpy>=1.24
 - networkx>=2.8.8
 - pandas>=2
 - ray-default
 - scipy>=1.1
 - seaborn>=0.13.2
 - sympy>=1.12
 - pvlib>=0.11.0
 - tqdm>=4.66.5
 - pyarrow
 - tensorboardX
 - netCDF4
 - mpi4py
 - numba
