#! /bin/bash

#SBATCH --job-name=diim_maps_1
#SBATCH -N1
#SBATCH --ntasks-per-node=48
#SBATCH --time=4:00:00
#SBATCH --account=OGS23_PRACE_IT
#SBATCH --partition=g100_usr_prod

export CINECA_SCRATCH=/g100_scratch/userexternal/csotolop
module purge
module load autoload
module load gcc/10.2.0
module load python/3.8.6--gcc--10.2.0
module load netcdf-fortran/4.5.3--openmpi--4.1.1--gcc--10.2.0
module load cmake/3.21.4
module load openblas/0.3.18--gcc--10.2.0
module load grads
module load nco/5.0.1--openmpi--4.1.1--gcc--10.2.0

export DIIM_PATH=/g100_work/OGS23_PRACE_IT/csoto/DIIM
export DIIM_ENV_PATH=/g100_work/OGS23_PRACE_IT/csoto/DIIM

date

export RANKS_PER_NODE=1
mpirun -n 48 /g100_work/OGS23_PRACE_IT/csoto/eat/eat_env/bin/python3 -W ignore /g100_work/OGS23_PRACE_IT/csoto/diim_matches/generate_matches.py

date
